apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/jwang8-wiq/my-first-argo-app
    targetRevision: HEAD
    path: k8s
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true