name: Deploy to Kubernetes via Argo CD
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML
        run: yamllint k8s/
      - name: Notify
        run: echo "Changes pushed. Argo CD will sync automatically."